### ISSUE TITLE
Vertical Images are displayed way to big in the editor

### ISSUE THREAD

**Issue by mj0stjo** [APSE-System/Immerscale#118]
![grafik](https://github.com/APSE-System/Immerscale/assets/47395845/4588bd6e-90cc-43e2-af0a-3d558cb10c73)

**Comment by MarcelQ5** [comment]
There is an additional problem with images in the preview. They also seem to be displayed as horizontal or vertical images randomly, some get totally stretched by the website to force them into horizontal orientation
![image](https://github.com/APSE-System/Immerscale/assets/30504097/7d14a01e-42bd-43d8-83bf-202ee15bb5d0)
